connect 'jdbc:derby://localhost:1527/metrodb;create=true;traceFile=trace.out;user=shibu;password=shibu';


create schema bank;

CREATE TABLE BANK.ACCOUNT (
  ACCOUNT_ID               INTEGER PRIMARY KEY,
  CUSTOMER_ID              INTEGER NOT NULL,
  ACCOUNT_TYPE             VARCHAR(100),
  INTEREST_RATE            INTEGER NOT NULL,
  BALANCE                  INTEGER NOT NULL,
  LAST_MODIFIED_DATETIME   DATE  DEFAULT CURRENT_DATE
);


CREATE TABLE BANK.CUSTOMER (
  CUSTOMER_ID             INTEGER PRIMARY KEY,
  CUSTOMER_NAME           VARCHAR(100),
  LAST_MODIFIED_DATETIME DATE  DEFAULT CURRENT_DATE
);


CREATE SEQUENCE hibernate_sequence
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
;


INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (401,301,'SAVINGS'      ,3,101 ,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (402,301,'RECURRING'    ,8,1011,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (403,301,'FIXED'        ,7,1012,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (404,302,'CURRENT'      ,2,1013,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (405,302,'SAVINGS'      ,3,101 ,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (406,303,'RECURRING'    ,8,1011,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (407,304,'FIXED'        ,7,1012,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (408,304,'CURRENT'      ,2,1013,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (409,304,'SAVINGS'      ,3,101 ,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (410,304,'RECURRING'    ,8,1011,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (411,305,'FIXED'        ,7,1012,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (412,306,'CURRENT'      ,2,1013,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (413,306,'SAVINGS'      ,3,101 ,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (414,307,'RECURRING'    ,8,1011,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (415,307,'FIXED'        ,7,1012,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (416,307,'CURRENT'      ,2,1013,CURRENT_DATE);


COMMIT;


INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (301,'SHIBU'            ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (302,'ARUN MOHAN'       ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (303,'MAYUR'            ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (304,'SRINIVAS'         ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (305,'SRIKAR'           ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (306,'RAGHUNATH'        ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (307,'RAHUL'            ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (308,'MOHANDAS GANDHI'  ,CURRENT_DATE);


COMMIT;
