connect 'jdbc:derby://localhost:1527/metrodb;create=true;traceFile=trace.out;user=shibu;password=shibu';


DELETE FROM BANK.CUSTOMER;

----------------------------------------------------------------------------------------------------------------------------------
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (301,'SHIBU'            ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (302,'ARUN MOHAN'       ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (303,'MAYUR'            ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (304,'SRINIVAS'         ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (305,'SRIKAR'           ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (306,'RAGHUNATH'        ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (307,'RAHUL'            ,CURRENT_DATE);
INSERT INTO BANK.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, LAST_MODIFIED_DATETIME) VALUES (308,'MOHANDAS GANDHI'  ,CURRENT_DATE);


----------------------------------------------------------------------------------------------------------------------------------
COMMIT;
