connect 'jdbc:derby://localhost:1527/metrodb;create=true;traceFile=trace.out;user=shibu;password=shibu';

DELETE FROM BANK.ACCOUNT;


----------------------------------------------------------------------------------------------------------------------------------
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (401,301,'SAVINGS'      ,3,101 ,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (402,301,'RECURRING'    ,8,1011,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (403,301,'FIXED'        ,7,1012,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (404,302,'CURRENT'      ,2,1013,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (405,302,'SAVINGS'      ,3,101 ,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (406,303,'RECURRING'    ,8,1011,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (407,304,'FIXED'        ,7,1012,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (408,304,'CURRENT'      ,2,1013,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (409,304,'SAVINGS'      ,3,101 ,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (410,304,'RECURRING'    ,8,1011,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (411,305,'FIXED'        ,7,1012,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (412,306,'CURRENT'      ,2,1013,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (413,306,'SAVINGS'      ,3,101 ,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (414,307,'RECURRING'    ,8,1011,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (415,307,'FIXED'        ,7,1012,CURRENT_DATE);
INSERT INTO BANK.ACCOUNT (ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, INTEREST_RATE, BALANCE, LAST_MODIFIED_DATETIME) VALUES (416,307,'CURRENT'      ,2,1013,CURRENT_DATE);


----------------------------------------------------------------------------------------------------------------------------------
COMMIT;
